sudo: required

services:
  - docker

before_install:
  - docker build -t steviebiddles/docker-fibonacci-tests -f ./client/Dockerfile.dev ./client

script:
  - docker run steviebiddles/docker-fibonacci-tests npm test -- --coverage

after_success:
  - docker build -t steviebiddles/docker-fibonacci-client ./client
  - docker build -t steviebiddles/docker-fibonacci-nginx ./nginx
  - docker build -t steviebiddles/docker-fibonacci-server ./server
  - docker build -t steviebiddles/docker-fibonacci-worker ./worker

  # Log into docker cli and push to hub.docker.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push steviebiddles/docker-fibonacci-client
  - docker push steviebiddles/docker-fibonacci-nginx
  - docker push steviebiddles/docker-fibonacci-server
  - docker push steviebiddles/docker-fibonacci-worker